Frontend/src/components/Footer.jsx
---
labels: ""
assignees: ""
---
---
- Updated:  Added smooth scroll-to-top functionality triggered when footer links are clicked.
---
- Test case 1:  Clicked on footer link → Page smoothly scrolled to top.
- Test case 2:  Tried on different sections → Scroll works consistently.
---
|No scroll on footer link click | smooth scroll|
| [Image] | [Image] |
---
---
- [] Created a new branch for PR
- [] Have stared the repository
- [] Follows [JavaScript Styleguide](CONTRIBUTING.md#javascript-styleguide)
- [] No console warnings/errors
- [] Commit messages follow [Git Guidelines](CONTRIBUTING.md#git-commit-messages)
=> added scroll up feture when click on footer links

Frontend/src/App.jsx, Frontend/src/components/BackToTopButton.jsx
---
title: "PR: Add Smooth Scroll 'Back to Top' Button"
labels: "good first issue, GSSoC-25, enhancement"
assignees: "abinayagoudjandhyala"
---
---
- Added: `BackToTopButton` component with smooth scroll functionality and OMEX-themed styling
- Updated: Integrated `BackToTopButton` into `App.jsx` to render globally
- Fixed: Improved navigation experience for long pages with a floating accessible button
---
- Test case 1: Scroll down past 300px, button appears as expected; clicking button smoothly scrolls to top
- Test case 2: Verified button focusable by keyboard and accessible via screen readers; responsive layout on desktop 
---
---
---
- This feature enhances user navigation on long content pages with minimal impact on performance. …
=> Feature Request: Add Smooth Scroll & “Back to Top” Button #10

BackEnd/.env.example, BackEnd/src/config/systemInstructions.js, BackEnd/src/controllers/ai.controller.js, BackEnd/src/routes/ai.routes.js, BackEnd/src/services/ai.service.js, Frontend/.env.example, Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.jsx, Frontend/src/components/Nav.jsx, Frontend/src/pages/CodeTools.jsx, Frontend/src/pages/SecurityScanner.jsx
---
name: Pull Request
title: "PR: Add Security Vulnerability Scanner Feature"
labels: "feature, security"
assignees: ""
---
- Added **Security Vulnerability Scanner** tool in frontend (navbar + tools menu).
- Integrated with backend Gemini response to display vulnerabilities.
- Created new route `/security-scanner` with clean UI/UX.
- Updated **isToolsActive** function to support scanner route.
- Ensured consistent design with other OMEX Code Tools.
---
- Test case 1: Navigate to `/security-scanner` → Scanner loads properly.
- Test case 2: Run backend scan → Vulnerabilities show formatted output.
- Test case 3: Checked responsiveness (desktop + mobile).
- Test case 4: Dark/Light theme compatibility verified.
---
| No …
=> added secuity scanner in tools properply

Frontend/.env.example, Frontend/src/components/Nav.jsx
---
name: fixed bugs in tools section
about: enhance the styling of the navbar
description:
the issue is fix the bug in "view all button" i have the fixed it and enhance the navbar styling by adding hover animation for the  elements
#20 
---
| [Image] | [Image] |
---
---
=> fix the navbar bugs and styling

Frontend/src/components/Nav.jsx
---
name: 📦 Pull Request
title: "PR: Added Cursor-Pointer for Tools and Company Dropdown"
labels: "level 1 | gssoc 25"
---
---
- Added: `cursor-pointer` to Tools and Company in Nav.jsx with tailwind css
- Fixed: Tools And Company Dropdowns
- Updated: Nav.jsx
---
| [https://drive.google.com/file/d/1uK8oGnkRG02vRsShmveJcWZWCF8PngRK/view?usp=sharing] | [https://drive.google.com/file/d/1zYFym0-LqCcLPqj0rYdJ564l5BgCxOKC/view?usp=sharing] |
---
=> Added the cursor-pointer feature to Tools and Company

Frontend/src/components/Faq.jsx, Frontend/src/pages/Home.jsx
Added responsive FAQ section for Home Page
=> added responsive FAQ section

Frontend/src/components/Loader.jsx
---
title: "PR: Add new crazy loader"
labels: **`Enhancement`**, **`GSSoC'25`**, **`LEVEL 3`**, **`Style Enhancement`**
assignees: "Amogh Kashyap S N"
---
---
- Added:  New dynamic and crazy loader component with multiple size options (small, medium, large, XL)
- Fixed: N/A
- Updated: N/A
---
---
**BEFORE**
https://github.com/user-attachments/assets/475d7bc6-d01e-45a3-b603-83c0fe00e0dd
**AFTER**
***LG***
https://github.com/user-attachments/assets/abe56a1d-d09d-4a71-9dc1-5b167e052f3d
***SM***
https://github.com/user-attachments/assets/c094ae22-5d53-46d2-8924-8104dae6d195
---
---
=> Added the new Loader

Frontend/src/pages/Home.jsx
---
title: "PR: No Duplicates of New Code Tools Section"
labels: "gssoc '25"
---
---
- Fixed: FeatureCards internal alignment and removal of duplicates in "New Code Tools" Section
- Updated: Home Page's "New Code Tools", removing duplicates
---
| <img width="1470" height="830" alt="Screenshot 2025-08-24 at 7 16 08 AM" src="https://github.com/user-attachments/assets/23a19d45-30b3-4a3f-8bf8-796925cbea18" /> | <img width="1470" height="831" alt="Screenshot 2025-08-24 at 7 15 32 AM" src="https://github.com/user-attachments/assets/110a3563-b0c2-4388-8c69-390e0fa7f58b" /> |
---
- Before, the Alignment of the buttons (Learn More) in Feature Cards Was Not Correct, I made them all aligned together in a …
=> No Duplicates of New Code Tools Section

Frontend/src/components/Navbar.jsx
---
labels: **`  good first issue  `**, **` enhancement  `**, **`  gssoc25  `**, **`  level 2  `**
assignees: "Amogh Kashyap S N"
---
---
- Added: New hover effect for navbar links and improved hamburger menu animation.
- Fixed: Inconsistent hover behavior and mobile navbar alignment issues.
- Updated: Navbar UI styling and responsive behavior for desktop and mobile.
---
---
** AFTER IMAGES**
***LG DEVICES***
https://github.com/user-attachments/assets/f687f02e-2201-4dec-af2a-a7e75f7b7267
CHANGES MADE: Changed the **HOVER** animation and the **DROP DOWN** made smoother and **DIFFERENT** color codes for different container …
=> Navbar enhanced

Frontend/src/components/Navbar.jsx
Description: Updated the main site title in the navbar to a larger font size for better visibility and emphasis.
This closes the issue #82
=>  Increased Navbar Title Font Size

BackEnd/src/services/ai.service.js, Frontend/package-lock.json, Frontend/package.json, Frontend/vite.config.js
Users were seeing uncomfortable text like "Senior Code Reviewer (7+ Years of Experience)" in code review responses.
Added a response cleaning function that filters out system instruction text before displaying to users.
- Added `cleanAIResponse()` function in AI service
- Applied cleaning to all AI response functions
- Improved user experience by showing only relevant content
- Tested locally with code review functionality
- Verified system instructions are filtered out
- I have shared the screenshot which consists of clean optimization part with no unnecessary intro.
=> fix: Remove unnecessary introductory text in optimization output

Frontend/src/App.jsx, Frontend/src/components/ContributorsLeaderboard.jsx, Frontend/src/components/Navbar.jsx
---
title: "PR: Added Contributors Leaderboard"
labels: ""
assignees: ""
---
---
=> Contributors Leaderboard added in Navbar

Frontend/package-lock.json, Frontend/package.json, Frontend/src/pages/Contact.jsx
---
labels: **`  Enhancement  `**, **`  GSSoC'25  `**, **`  Level 3  `**, **`  Style Enhancement  `**
assignees: "Amogh Kashyap S N"
---
---
- Added: Smooth animations and applied the defined color codes to align with the overall theme.
- Fixed: Error handling on the Contact Us page for better user feedback and reliability.
- Updated: Enhanced the UI design of the Contact Us page to improve usability and visual appeal.
---
---
**LG devices**
https://github.com/user-attachments/assets/6208b6e5-5ec9-4116-95bf-1e3de7f4e66d
---
**SM devices**
https://github.com/user-attachments/assets/4033e34e-0c36-4279-aa61-cfc8cd30b632
--- …
=> Enhanced the UI of contact Us page

Frontend/package-lock.json, Frontend/src/components/BackToTopButton.jsx, Frontend/src/components/FeedbackForm.jsx
---
title: "PR: Fix feedback & scroll-to-top button overlap (#32)"
labels: "bug"
assignees: ""
---
- Closes #32
---
- Fixed: Overlap issue between feedback button and scroll-to-top button.  
- Updated:  
- Feedback button positioned at `fixed bottom-6 right-30`.  
- Scroll-to-top button positioned at `fixed bottom-6 right-9`.  
- Ensured proper spacing and visibility across devices.
---
- **Test case 1**: Scroll down the page → scroll-to-top button appears → both buttons do not overlap. ✅  
- **Test case 2**: Resize window → both buttons maintain proper spacing. ✅  
---
**Before:**
**After:**
---
---
---
- Minor UI fix only, no breaking changes.
=> fix: resolve feedback button and scroll-to-top overlap (#32)

Frontend/.env.example, Frontend/src/components/ContributorsLeaderboard.jsx
---
labels: ` Enhancement `, ` GSSoC25 `, ` Level 3 `
assignees: "Amogh Kashyap S N"
---
---
- Added: Real-time leaderboard page with contributor data fetched using `gssoc` tag.  
- Added: Points system based on PR levels (Level 1, Level 2, Level 3).  
- Added: Search functionality to quickly find contributors.  
- Added: Pagination support for smooth navigation across large contributor lists.  
- Fixed: Removed inconsistencies in displaying contributor data across different sections.  
- Fixed: Improved responsiveness and UI alignment issues on smaller screens.  
- Updated: Integrated live GitHub API fetch to reflect real-time contributions.  
- Updated: Enhanced leaderboard UI for better readability …
=> Added Real-Time Leaderboard with Search & Pagination

Frontend/src/components/ContributorsLeaderboard.jsx
---
labels:  ` Enhancement `, ` GSSoC25 `, ` Level 3 `
assignees: Amogh Kashyap S N
---
---
- Added: [Description]
- Fixed: [Description]
- Updated: [Description]
---
---
https://github.com/user-attachments/assets/4a611c74-2fcc-40cb-80d2-828a44e76daf
---
---
* ` GSSoC25 `
* ` Level 2 `
=> Resolved the shimmer UI

Frontend/src/pages/About.jsx
#117
---
* Added icons directly in the *Tech Stack* section for better visual representation.
---
* Verified that icons are displaying correctly in the Tech Stack section.
---
| Before                               | After                              |
| ------------------------------------ | ---------------------------------- |
| <img width="1541" height="402" alt="image" src="https://github.com/user-attachments/assets/df06ac7c-deae-4eb2-8a66-15246ce1d18d" /> | ![WhatsApp Image 2025-08-31 at 14 41 08_782d0067](https://github.com/user-attachments/assets/6f4bbdbd-b83a-4881-a5e6-d9c40d4c888d)
---
---
---
* This improves *readability and aesthetics* of the Tech Stack section.
---
👉 Do you want me to also write the *commit message* for this PR so it’s ready to push?
=> Added icons in tech stack section

Frontend/src/pages/Home.jsx
Issue #79 Resolved
**Before:**
- The service cards were completely static.
- On hover, there was no animation or interaction.
- The overall UI looked a little flat and less engaging.
**After (Now):**
- Added a smooth 3D lift effect on hover.
- When a user hovers on a card, it slightly lifts up with a clean transition.
- The design now feels more modern and interactive.
**Benefits of this Change:**
- Makes the UI more visually appealing.
- Improves user experience by adding interactivity.
- Gives a premium and professional feel to the website.
- Subtle micro-interactions like this keep users engaged for longer.
=> Add 3D Styling and Hover Effects to "How It Works" Section #79

Frontend/src/components/Navbar.jsx
---
name: "📦 Updated drop down for both of them i.e for Tool and Compony"
title: "PR: Solved the issue of dropdown "
labels: "Level 2
Medium
bug
Something isn't working
assignees: "Aashutosh kumar bahrdwaj"
---
---
=> Updated drop down for both of them i.e for Tool and Compony

Frontend/src/components/Footer.jsx
---
- Updated: Replace Twitter icon with BsTwitterX in Footer component
---
---
| [Image] | [Image] |
---
---
=> Replace Twitter icon with BsTwitterX in Footer component

Frontend/src/pages/PrivacyPolicy.jsx
---
labels: ` Enhancement `, ` GSSoC25 `, ` Level 3 `
assignees: Amogh 
---
---
- Refactored Privacy Policy page to improve UI/UX.
- Applied global theme styles (#000000, #60A5FA, #F4FDFF, #FFFFFF).
- Improved typography and spacing for better readability.
- Added structured headings (h2, h3) for content hierarchy.
- Enhanced responsiveness across mobile, tablet, and desktop.
- Introduced subtle highlights (cards/dividers/backgrounds) for key sections.
- (Optional) Added a table of contents with anchor links for easier navigation.
- Page was plain and text-heavy.
- No clear structure or visual hierarchy (headings, spacing, typography).
- Inconsistent with theme colors and design language.
- Lacked …
=> Refactored Privacy page

Frontend/src/components/CodeEditor.jsx, Frontend/src/pages/Contact.jsx
=> Copy button For code editor

Frontend/index.html
My issue was #159 
---
title: "PR: PR: Fix index.html paths, add noscript fallback, improve structured data
labels: "Bug Level 3"
assignees: ""
---
Connected to #159
-Fixed favicon and main JS file paths (changed from root / to relative ./).
-Added <noscript> fallback for users with JavaScript disabled.
-Improved structured data by adding url and aggregateRating.
Tested manually:
-Opened project locally → favicon and JS load correctly.
-Disabled JavaScript in browser → fallback message appears.
(Not applicable — no visual UI change, only backend HTML improvements)
---
No docs needed for this change
##Screenshot
No breaking changes. Improves SEO, accessibility, and deployment compatibility.
=> Fix(index.html): use relative paths, add noscript fallback, improve structured data

Frontend/src/pages/CodeBeautifier.jsx, Frontend/src/pages/ErrorDebugger.jsx, Frontend/src/pages/PerformanceAnalyzer.jsx, Frontend/src/pages/SecurityScanner.jsx, Frontend/src/pages/TestCaseGenerator.jsx
---
Pull Request
---
---
- Added the example code for all the different languages in the dropdown menu for the 5 different features
---
Have added the snippets for Python as example. It is applicable to the other languages present.
=> Added example code for the 5 features

BackEnd/src/controllers/ai.controller.js, BackEnd/src/controllers/media.controller.js
The current media.controller.js works as intended but contains repeated logic for text limiting, error handling, and summarization. This duplication makes the file longer and harder to maintain.
Added a reusable limitTextLength utility for safe, consistent text handling across all sources.
Centralized error handling and logging with a standardized format.
Simplified file-type checks in summarizeFile using cleaner conditions.
Applied default values (summaryLength, summaryType) inline via destructuring to reduce boilerplate.
Maintained all existing functionality (PDF, image, text, and YouTube summarization).
Removes duplicated code for:
Text length limiting.
Empty input validation.
Creates a more consistent structure across summarization handlers.
Easier to maintain, debug, and extend in …
=> Refactor media.controller.js for cleaner, DRYer summarization logic

Frontend/src/App.jsx, Frontend/src/components/FeedbackButton.jsx, Frontend/src/components/Footer.jsx, Frontend/src/components/Navbar.jsx, Frontend/src/pages/CodeBeautifier.jsx, Frontend/src/pages/CodeCompare.jsx, Frontend/src/pages/CodeComplexity.jsx, Frontend/src/pages/CodeGenerator.jsx, Frontend/src/pages/CodeOptimizer.jsx, Frontend/src/pages/Contact.jsx, Frontend/src/pages/ContentSummarizer.jsx, Frontend/src/pages/DependencyScanner.jsx, Frontend/src/pages/ErrorDebugger.jsx, Frontend/src/pages/Feedback.jsx, Frontend/src/pages/PerformanceAnalyzer.jsx, Frontend/src/pages/SecurityScanner.jsx, Frontend/src/pages/TestCaseGenerator.jsx
Description
This PR implements a feedback feature to allow users to share their experiences, report bugs, and suggest improvements while using OMEX.
Changes Made
-Added a “Feedback” button in the footer and Company dropdown in the navbar for visibility.
-Added Feedback option on every tool page, so users can quickly provide feedback after using a tool.
-Implemented a Feedback Form Page with the following fields:
-Name (optional) – text input
-Email (optional) – text input
-Feedback Type (Bug Report, Feature Request, General Feedback)
-Feedback Message Field(required) – textarea
-Overall Rating – star rating input
-Added Submit button with form validation (feedback is required).
-After submitting, a Thank You message is displayed to confirm submission with a "Submit Another Feedback" …
=>  Added Feedback Feature

BackEnd/.env.example, BackEnd/src/app.js, BackEnd/src/config/systemInstructions.js, BackEnd/src/controllers/ai.controller.js, BackEnd/src/routes/ai.routes.js, BackEnd/src/services/ai.service.js, Frontend/.gitignore, Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.jsx, Frontend/src/components/CodeMetricsAnalyzer.jsx, Frontend/src/components/Footer.jsx, Frontend/src/components/Nav.jsx, Frontend/src/components/Navbar.jsx, Frontend/src/pages/CodeMetrics.jsx, Frontend/src/pages/CodeTools.jsx, Frontend/vite.config.js
title: "PR: Added CodeMetricsAnalyzer Feature"
labels: "enhancement"
assignees: " @Roshansuthar1105
"
- Added: `CodeMetricsAnalyzer` backend service to analyze code complexity.
- Added: Frontend integration to display complexity metrics dynamically.
- Fixed: Minor bugs in existing analyzer for better performance.
- Updated: README with instructions to use CodeMetricsAnalyzer.
- Test case 1: Run analyzer on sample JS file → metrics displayed correctly.
- Test case 2: Run analyzer on empty file → handled gracefully without crashing.
[▶️ View CodeMetricsAnalyzer UI](https://drive.google.com/file/d/1emLg_xLBmeyBoZeZv-fZyrKUflAQA-aV/view?usp=sharing)
- Backend must be running to access the CodeMetricsAnalyzer.
- Designed to be extensible …
=> ✨ Added CodeMetricsAnalyzer feature

Frontend/MOBILE_TOUCH_FIX_PR.md, Frontend/package-lock.json, Frontend/src/components/CodeEditor.jsx, Frontend/src/index.css, Frontend/src/pages/CodeBeautifier.jsx, Frontend/src/pages/ErrorDebugger.jsx, Frontend/src/pages/PerformanceAnalyzer.jsx, Frontend/src/pages/SecurityScanner.jsx, Frontend/src/pages/TestCaseGenerator.jsx, Frontend/src/utils/mobileUtils.js, MOBILE_TOUCH_FIX_DOCUMENTATION.md
closes #237 
🔧 Key Changes Made:
1. Enhanced Touch Event Handling
Added [onTouchStart](vscode-file://vscode-app/c:/Users/Devansh/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) and [onTouchEnd](vscode-file://vscode-app/c:/Users/Devansh/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) handlers to all Clear buttons
Implemented proper event prevention to avoid conflicts
Added visual feedback with scale animations on touch
2. Mobile-Optimized Button Design
Increased button size to minimum 44x44px (WCAG guidelines)
Added mobile-specific CSS properties:
touch-manipulation for better touch response
[WebkitTapHighlightColor: …
=> fix mobile functionality

README.md
---
labels: ""
assignees: ""
---
closing #221 
---
updated folder structre
--added frontend folder structre
--added inside src folder structre
---
---
---
=> ✨ updated the folder structre in readme.md
